apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: mops-vscale
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: ag
  verticalScaling:
    mssqlserver:
      resources:
        requests:
          memory: "4Gi"
          cpu: 2
        limits:
          memory: "4Gi"
    coordinator:
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
    arbiter:
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
  timeout: 2m
  apply: IfReady