apiVersion: v1
stringData:
  password: very-strong-pass
  username: default
kind: Secret
metadata:
  name: rd-auth-secret
  namespace: demo
type: kubernetes.io/basic-auth
---

apiVersion: v1
stringData:
  password: very-strong-pass
  username: postgres
kind: Secret
metadata:
  name: pg-auth-secret
  namespace: demo
type: kubernetes.io/basic-auth