# provisioning:

  # configuration:
  #   secretName: ms-custom-config
  #   inline:
  #     mssql.conf: |-
  #       [memory]
  #       memorylimitmb = 2511
  #       [network]
  #       tcpport = 1433

#   ➤ kubectl view-secret -n demo ms-custom-config -a
# mssql.conf='[network]
# tlsprotocols = 1.2

# [language]
# lcid = 1033

# [memory]
# memorylimitmb = 2304
# '


# ➤ kubectl view-secret -n demo standalone-9188a3 -a
# mssql.conf='[language]
# lcid = 1033
# [memory]
# memorylimitmb = 2511
# [network]
# tcpport = 1433
# tlsprotocols = 1.2
# '




apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: configure-1-only-apply
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: standalone
  configuration:
    applyConfig:
      mssql.conf: |-
        [sqlconnector]
        logginglevel = 0
  timeout: 5m
  apply: IfReady
---


# ➤ kubectl view-secret -n demo standalone-9188a3 -a
# mssql.conf='[language]
# lcid = 1033
# [memory]
# memorylimitmb = 2511
# [network]
# tcpport = 1433
# tlsprotocols = 1.2
# [sqlconnector]
# logginglevel = 0



apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: configure-2-only-config
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: standalone
  configuration:
    configSecret:
      name: ms-new-custom-config
  timeout: 5m
  apply: IfReady

# ➤ kubectl view-secret -n demo ms-new-custom-config -a
# mssql.conf='[sqlagent]
# enabled = true'


// verify 
# ➤ kubectl view-secret -n demo standalone-9188a3 -a
# mssql.conf='[language]
# lcid = 1033
# [memory]
# memorylimitmb = 2511
# [network]
# tcpport = 1433
# tlsprotocols = 1.2
# [sqlconnector]
# logginglevel = 0


---
apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: configure-3-remove-and-apply
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: standalone
  configuration:
    removeCustomConfig: true
    applyConfig:
      mssql.conf: |-
        [memory]
        memorylimitmb = 2096
  timeout: 5m
  apply: IfReady

# only apply:
# mssql.conf: |-
#   [memory]
#   memorylimitmb = 2096

---


apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: configure-4-config-and-apply
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: standalone
  configuration:
    configSecret:
      name: ms-new-custom-config2
    applyConfig:
      mssql.conf: |-
        [network]
        tcpport = 1433
  timeout: 5m
  apply: IfReady

# ➤ kubectl view-secret -n demo ms-new-custom-config2 -a
# mssql.conf='[memory]
# memorylimitmb = 4096
# [sqlagent]
# enabled = false
# '

# config:
# [memory]
# memorylimitmb = 4096
# [sqlagent]
# enabled = false
# apply:
#   [network]
#   tcpport = 1433
#   [memory]
#   memorylimitmb = 2096

---


apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: configure-5-only-apply
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: standalone
  configuration:
    applyConfig:
      mssql.conf: |-
        [sqlconnector]
        logginglevel = 1
        [memory]
        memorylimitmb = 2097
  timeout: 5m
  apply: IfReady


# config:
# [memory]
# memorylimitmb = 4096
# [sqlagent]
# enabled = false
# apply:
#   [network]
#   tcpport = 1433
#   [sqlconnector]
#   logginglevel = 1
#   [memory]
#   memorylimitmb = 2097


# final config:
# [memory]
# memorylimitmb = 2097
# [sqlagent]
# enabled = false
# [network]
# tcpport = 1433
# [sqlconnector]
# logginglevel = 1
---