apiVersion: v1
kind: Secret
metadata:
  name: proxysql-custom-config
  namespace: demo  # change if needed
type: Opaque
stringData:
  AdminVariables.cnf: |
    admin_variables=
    {
        checksum_mysql_query_rules: true
        refresh_interval: 2000
        connect_timeout_server: 3000
    }
  MySQLQueryRules.cnf: |
    mysql_query_rules=
    (
        {
            rule_id=1
            active=1
            match_pattern="^SELECT .* FOR UPDATE$"
            destination_hostgroup=2
            apply=1
        },
        {
            rule_id=2
            active=1
            match_pattern="^SELECT"
            destination_hostgroup=3
            apply=1
        }
    )
  MySQLUsers.cnf: |
    mysql_users=
    (
        {
            username = "user2"
            password = "pass2"
            default_hostgroup = 2
            active = 1
        },
        {
            username = "user3"
            password = "pass3"
            default_hostgroup = 2
            max_connections=1000      
            default_schema="test"
            active = 1
        },
        { 
            username = "user4" 
            password = "pass4" 
            default_hostgroup = 0 
            active = 1 
            comment = "hello all"
        }
    )
  MySQLVariables.cnf: |
    mysql_variables=
    {
        max_connections=1024
        default_schema="information_schema"
    }
